#!/bin/bash
#!/bin/bash

# ANSI

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
YELLOW='\033[33m'
MAGNETA='\033[35m'
CYAN='\033[36m'
NC='\033[0m' # Restablecer color


# Solicitar al usuario el primer numero
echo -e "\e[34m|-----------------------------|\e[0m"
read -p "$(echo -e "${CYAN}Ingresa el primer numero:${NC} ")" num1
# Solicitar al usuario el segundo numero
echo -e "\e[34m|-----------------------------|\e[0m"
read -p "$(echo -e "${CYAN}Ingresa el segundo numero:${NC} ")" num2

# Mostrar las opciones disponibles
echo -e "\e[34m|-----------------------------|\e[0m"
echo -e "\e[34m|\e[0m\e[36mSeleccionar la operacion:\e[0m"
echo -e "\e[34m|\e[0m\e[36m1.\e[0m \e[35mSuma\e[0m"
echo -e "\e[34m|\e[0m\e[36m2.\e[0m \e[35mResta\e[0m"
echo -e "\e[34m|\e[0m\e[36m3.\e[0m \e[35mMultiplicacion\e[0m"
echo -e "\e[34m|\e[0m\e[36m4.\e[0m \e[35mDivision\e[0m"
echo -e "\e[34m|-----------------------------|\e[0m"

# Solicitar al usuario que elija una opcion
echo -e "\e[34m|-------------------------------------------------------|\e[0m"
read -p "$(echo -e "${CYAN} Ingresa el numero de la operacion que desea realizar:${NC} ")" opcion
echo -e "\e[34m|-------------------------------------------------------|\e[0m"

# Realizar la operación seleccionada
case $opcion in
  1) resultado=$(($num1 + $num2))
     operacion="suma"
     ;;
  2) resultado=$(($num1 - $num2))
     operacion="resta"
     ;;
  3) resultado=$(($num1 * $num2))
     operacion="multiplicación"
     ;;
  4) resultado=$(echo "scale=2; $num1 / $num2" | bc)
     operacion="división"
     ;;
  *)
     echo -e "\e[31----------------\e[0m"
     echo -e "\e[31mOpción inválida\e[0m"
     echo -e "\e[31----------------\e[0m"
     exit 1
     ;;
esac

# Mostrar el resultado
echo -e "\e[34m|------------------------------------------------------|\e[0m"
echo -e "\e[36m    El resultado de la $operacion es:\e[0m \e[32m$resultado\e[0m"
echo -e "\e[34m|------------------------------------------------------|\e[0m"
